package com.marklogic.spring.web.servlet.mvc;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.User;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import com.marklogic.spring.http.proxy.HttpProxy;

/**
 * Controller that handles the login/logout endpoints expected by the UI generated by
 * https://github.com/marklogic/slush-marklogic-node. In addition, it also proxies all REST API requests to MarkLogic.
 * 
 * This does not have the Controller annotation on it; it is expected that a user will subclass this and add additional
 * request handlers, and thus the Controller annotation can be added to the subclass.
 */
public class SlushUiController {

    protected Logger logger = LoggerFactory.getLogger(getClass());

    @Autowired
    private HttpProxy httpProxy;

    /**
     * Assumes that the root URL should use a template named "index", which presumably will setup the Angular app.
     */
    @RequestMapping(value = "/", method = RequestMethod.GET)
    public String index() {
        return "index";
    }

    /**
     * The UI checks the user's login status via this endpoint.
     */
    @RequestMapping(value = "/api/user/status", method = RequestMethod.GET)
    @ResponseBody
    public String userStatus(HttpServletResponse response) {
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        response.setContentType("application/json");
        if (auth != null && auth.isAuthenticated()) {
            String username = null;
            if (auth.getPrincipal() instanceof User) {
                username = ((User) auth.getPrincipal()).getUsername();
            } else {
                username = auth.getPrincipal().toString();
            }
            return String.format("{\"authenticated\":true, \"username\":\"%s\"}", username);
        }
        return "{\"authenticated\":false}";
    }

    /**
     * Assumes that Spring Security is configured to use a custom form for a login page with a URL of "/login", with the
     * template for that form being named "login".
     */
    @RequestMapping(value = "/login", method = RequestMethod.GET)
    public String showLoginPage() {
        return "login";
    }

    /**
     * The UI logs the user out via this endpoint.
     */
    @RequestMapping(value = "/api/user/logout", method = RequestMethod.GET)
    @ResponseBody
    public void logout() {
        SecurityContextHolder.clearContext();
    }

    /**
     * Proxies all REST API requests to MarkLogic via an instance of HttpProxy.
     */
    @RequestMapping("/v1/**")
    @ResponseBody
    public void proxy(HttpServletRequest httpRequest, HttpServletResponse httpResponse) {
        httpProxy.proxy(httpRequest, httpResponse, "Content-type");
    }

    public HttpProxy getHttpProxy() {
        return httpProxy;
    }

    public void setHttpProxy(HttpProxy httpProxy) {
        this.httpProxy = httpProxy;
    }
}
